### ISSUE TITLE
Gamepad support

### ISSUE THREAD

**Issue by 0kie** [Drahsid/HybridCamera#1]
When selecting keys for legacy mode only kb+m buttons show up, making it impossible to use this plugin while using a gamepad

**Comment by Drahsid** [comment]
I think this mod is (mostly) redundant for controller players who use legacy mode, since they already have the full range of movement. Are you wanting to be able to rotate your character to match the view with the right stick?

**Comment by 0kie** [comment]
> Are you wanting to be able to rotate your character to match the view with the right stick, while maintaining the full range of movement?
Exactly that, standard mode camera is superior for dodging gaze mechanics for example, while legacy mode allows the full range of movement

**Comment by SparrowSteele** [comment]
any update on gamepad support? This would be very helpful for TOP monitors and DSR gazes

**Comment by Drahsid** [comment]
Sorry, I don't have any progress on this. I'll update this issue when I do.

**Comment by GoblinGuide** [comment]
This would also be mega-helpful for melees in Aloalo Criterion (for the boss with the Mustadio rings) - literally asking for a friend because I'm on kb/m myself, but I figured one more ping couldn't hurt...

**Comment by Drahsid** [comment]
Just a small update, I have done a bunch of reverse engineering on the code and structures which handle player movement. I something which may work, but I need to ensure it doesn't lead to situations which would allow the player to cheat. Hopefully I can get this out soon.

**Comment by SparrowSteele** [comment]
Youre a king for looking into it thanks mate, any updates on how its currently looking?

**Comment by Drahsid** [comment]
The most recent commits implemented gamepad support, and the update should be available on Dalamud. Closing this issue.
