### ISSUE TITLE
Doesn't quite work as expected on ice

### ISSUE THREAD

**Issue by retep998** [Drahsid/HybridCamera#2]
During combat phases with ice, when using legacy mode normally I will always move relative to the camera, but with this plugin it seems that it switches to legacy immediately *after* I press the movement key and the direction of sliding has already snapshotted, thus I end up sliding relative to my character and not my camera.

**Comment by Drahsid** [comment]
I haven't experienced this. What config options are you using?

**Comment by retep998** [comment]
![image](https://user-images.githubusercontent.com/666308/228474176-a56d613e-aa99-465c-afa7-393f0ef127dc.png)

In fights when there is ice, like the final fight of Euphrosyne, when I press forward without this plugin (just using legacy movement), I will slide in the direction that the camera is facing. When using this plugin with those settings, I will slide in the direction that my character is facing (which is towards the boss, and not where my camera is pointing).

**Comment by Drahsid** [comment]
Sorry for the delay on this update. I looked into this a while ago, figured out what was happening, then totally forgot to comment on this. The ice sliding effect moves you in the direction that your character attempts to move. This behavior is the same on standard and legacy mode, where the only difference is that on standard mode, your character moves in the direction they are facing, and in legacy, they move towards the camera. Pretty much, if you want to move in the direction of the camera, you need to be in legacy mode. I personally can't replicate this any more, so I may have accidentally fixed it at some point, but my theory is that you were somehow in standard mode at the moment you began moving. Auto-run maybe?

**Comment by retep998** [comment]
I should be in legacy while moving and standard while standing still, but if I push a button to move while on ice, then before this mod has a chance to set my character to legacy mode, the game will already have read that I'm still in standard mode and slide according to my character's direction instead of my camera's direction. I want to be able to slide like I'm in legacy mode, but this mod just reacts too late to be able to switch to legacy mode before the ice sliding direction is determined.

I can still easily replicate this, just did it the other day in Euphrosyne on the final boss.

**Comment by Drahsid** [comment]
I have had an extremely pedantic time replicating this. It requires a pretty technical order-of-events to happen.

> but this mod just reacts too late to be able to switch to legacy mode before the ice sliding direction is determined.
This mod has no latency (besides that of the on-frame callback.) To trigger this particular issue requires you to have stopped pressing the movement input on the frame that applies the sliding effect (you actually move normally for a frame on ice in many cases.)

There are a couple ways that I could fix this through trickery, but it might be best to use my hook into the movement code to try and do this beforehand. This probably won't fix this issue in the cases that movement is done server side (though there are very few instances of this lol). That said, this could cause some other issues, so I will have to test around with it. I'll release an update if it works out.

**Comment by Drahsid** [comment]
This should be fixed in the most recent update. Reopen this issue if something similar pops up!
